version: "3"
services:
 db:
  image: webreport
  container_name: webreport
  hostname: web
  restart: always
  volumes:
   - "$PWD":/var/www/html
    
  ports:
   - "80:80"
   
   #docker run -d -p 82:80  -v "$PWD":/var/www/html www18
